import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("dashboard", "routes/dashboard.tsx"),
  route("favorites", "routes/favorites.tsx"),
  route("recent", "routes/recent.tsx"),
  route("docs", "routes/docs.tsx"),
  route("analyze", "routes/analyze.tsx"),
  route("jwt-analyzer", "routes/jwt-analyzer.tsx"),
  route("jwt-generator", "routes/jwt-generator.tsx"),
  route("jwt-debugger", "routes/jwt-debugger.tsx"),
  route("jwt-best-practices", "routes/jwt-best-practices.tsx"),
  route("password-checker", "routes/password-checker.tsx"),
  route("hash-tools", "routes/hash-tools.tsx"),
  route("base64-tools", "routes/base64-tools.tsx"),
  route("cors-checker", "routes/cors-checker.tsx"),
  route("aes-encryption", "routes/aes-encryption.tsx"),
  route("rsa-generator", "routes/rsa-generator.tsx"),
  route("ssl-inspector", "routes/ssl-inspector.tsx"),
  route("http-builder", "routes/http-builder.tsx"),
  route("data-sanitizer", "routes/data-sanitizer.tsx"),
  route("api-security", "routes/api-security.tsx"),
  route("privacy-analyzer", "routes/privacy-analyzer.tsx"),
  route("certificate-decoder", "routes/certificate-decoder.tsx"),
  route("subnet-calculator", "routes/subnet-calculator.tsx"),
  route("regex-tester", "routes/regex-tester.tsx"),
  route("dns-lookup", "routes/dns-lookup.tsx"),
  route("url-parser", "routes/url-parser.tsx"),
  route("uuid-generator", "routes/uuid-generator.tsx"),
  route("text-diff", "routes/text-diff.tsx"),
  route("password-generator", "routes/password-generator.tsx"),
  route("totp-generator", "routes/totp-generator.tsx"),
  route("timestamp-converter", "routes/timestamp-converter.tsx"),
  route("json-formatter", "routes/json-formatter.tsx"),
  route("csp-generator", "routes/csp-generator.tsx"),
  route("hmac-generator", "routes/hmac-generator.tsx"),
  route("url-encoder", "routes/url-encoder.tsx"),
  route("secret-generator", "routes/secret-generator.tsx"),
  route("html-entities", "routes/html-entities.tsx"),
  route("color-converter", "routes/color-converter.tsx"),
  route("caesar-cipher", "routes/caesar-cipher.tsx"),
  route("xor-cipher", "routes/xor-cipher.tsx"),
  route("base-converter", "routes/base-converter.tsx"),
  route("hash-identifier", "routes/hash-identifier.tsx"),
] satisfies RouteConfig;
